on:
  push:
    branches: [master, dev/*]
  pull_request:
    branches: [master, dev/*]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Run angular checks (tests, lint, ...)    
        working-directory: memento-front
        run: |
          cp src/environments/auth_config.json.ini src/environments/auth_config.json 
          npm ci
          npm run test:prod
          ng lint
